apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: default
data:
  log_level: "INFO"
  port: "5000"
  greeting_header: "Welcome to our Custom Application"
  log_file: "/app/logs/app.log" 