apiVersion: v1
kind: Pod
metadata:
  name: flask-app
  labels:
    app: flask-app
spec:
  containers:
  - name: flask-app
    image: flask-app:latest
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 5000
    volumeMounts:
    - name: logs-volume
      mountPath: /app/logs
    - name: config-volume
      mountPath: /app/config
    env:
    - name: LOG_LEVEL
      valueFrom:
        configMapKeyRef:
          name: app-config
          key: log_level
    - name: PORT
      valueFrom:
        configMapKeyRef:
          name: app-config
          key: port
    - name: GREETING_HEADER
      valueFrom:
        configMapKeyRef:
          name: app-config
          key: greeting_header
    - name: LOG_FILE
      valueFrom:
        configMapKeyRef:
          name: app-config
          key: log_file
  volumes:
  - name: logs-volume
    emptyDir: {}
  - name: config-volume
    configMap:
      name: app-config 