apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
  labels:
    app: flask-app
spec:
  selector:
    app: flask-app
  type: ClusterIP
  sessionAffinity: None
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
    name: http 